default:
	cd filetest; make

clean:
	cd filetest; make clean

run:
# 	cd ../../bin; dlxsim -x os.dlx.obj -a -D F -u filetest.dlx.obj
	cd ../../os; make; cd ../bin; dlxsim -x os.dlx.obj -a -D F -u filetest.dlx.objj; ee469_fixterminal
