flat:
	mainframer.sh 'cd os && make clean'
	mainframer.sh 'cd os && make'
	mainframer.sh 'cd apps/fdisk && make clean'
	mainframer.sh 'cd apps/fdisk && make'
	mainframer.sh 'cd bin && dlxsim -x os.dlx.obj -a -D F -u fdisk.dlx.obj'
# 	mainframer.sh 'cd bin && dlxsim -x os.dlx.obj -a -u makeprocs.dlx.obj 30 hello_world.dlx.obj'
