q2:
	mainframer.sh 'cd os && make clean'
	mainframer.sh 'cd os && make'
	mainframer.sh 'cd apps/q2 && make clean'
	mainframer.sh 'cd apps/q2 && make'
	mainframer.sh 'cd apps/q2 && make run'

q3:
	mainframer.sh 'cd os && make clean'
	mainframer.sh 'cd os && make'
	mainframer.sh 'cd apps/q3 && make clean'
	mainframer.sh 'cd apps/q3 && make'
	mainframer.sh 'cd apps/q3 && make run'

q4:
	mainframer.sh 'cd os && make clean'
	mainframer.sh 'cd os && make'
	mainframer.sh 'cd apps/q4 && make clean'
	mainframer.sh 'cd apps/q4 && make'
	mainframer.sh 'cd apps/q4 && make run'

clean:
	mainframer.sh 'cd apps/q2 && make clean'
	mainframer.sh 'cd apps/q3 && make clean'
	mainframer.sh 'cd apps/q4 && make clean'
	mainframer.sh 'cd os && make clean'