default:
	mainframer.sh 'cd os && make clean'
	mainframer.sh 'cd os && make'
	mainframer.sh 'cd apps/q2 && make clean'
	mainframer.sh 'cd apps/q2 && make'
	mainframer.sh 'cd apps/q2 && make run'

clean:
	mainframer.sh 'cd apps/q2 && make clean'
	mainframer.sh 'cd os && make clean'